print("Written by: Mehki, Gwen, and Wrane")
print("Title: The Story of the Three LIttle Pigs")
print("Setting: Piggiesville, Texas")
print("Pigstein 'PigTom' Piggerton, The Home Grown Texan")
print("Pigstein the was the star quaterback of his town, his two brother were jealous of his fame and plotted to take em. Pigglebottom and Pigshawn Jr. attempted to get Pigstein's cleats so he can't play in the final game")
